import { ArrowRight, Bell, ChevronRight, Search, Sparkles } from 'lucide-react'
import { FormEvent, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useApp } from '../App'
import { GuidedWizard } from '../components/GuidedWizard'
import { ServiceCard } from '../components/ServiceCard'
import { categories, services } from '../data/services'
import { storage } from '../utils/storage'

const filters=[{id:'all',label:'ทั้งหมด'},{id:'citizen',label:'ประชาชนทั่วไป'},{id:'lawyer',label:'ทนายความ'},{id:'officer',label:'เจ้าหน้าที่'}]
export function HomePage(){const nav=useNavigate();const {user}=useApp();const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const featured=useMemo(()=>services.filter(s=>s.featured&&(filter==='all'||s.audience.includes(filter as never)||s.audience.includes('all'))),[filter]);const favorites=services.filter(s=>storage.favorites().includes(s.id));const recent=services.filter(s=>storage.recent().includes(s.id)).sort((a,b)=>storage.recent().indexOf(a.id)-storage.recent().indexOf(b.id));const submit=(e:FormEvent)=>{e.preventDefault();if(query.trim())nav(`/search?q=${encodeURIComponent(query.trim())}`)}
return <><section className="hero"><div className="hero-orb one"></div><div className="hero-orb two"></div><div className="container hero-inner"><div className="hero-copy"><div className="hero-label"><Sparkles/> เข้าถึงบริการศาลได้ง่ายขึ้น</div><h1>วันนี้คุณต้องการ<br/><em>ทำอะไรเกี่ยวกับศาล?</em></h1><p>ค้นหาและเข้าถึงบริการออนไลน์ของศาลได้จากที่เดียว<br/>ไม่ต้องจำชื่อระบบ เพียงบอกสิ่งที่คุณต้องการทำ</p><form className="hero-search" onSubmit={submit}><Search/><input aria-label="ค้นหาบริการ" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา เช่น ตรวจสอบคดี / ยื่นคำร้อง / ขอเอกสาร"/><button>ค้นหา</button></form><div className="popular"><span>ค้นหายอดนิยม:</span>{['ตรวจสอบคดี','วันนัด','ชำระค่าธรรมเนียม'].map(x=><button key={x} onClick={()=>nav(`/search?q=${x}`)}>{x}</button>)}</div></div><div className="hero-visual" aria-hidden="true"><div className="justice-illustration"><div className="scale-icon">⚖</div><div className="court-pill"><span>✓</span><div><b>รวมทุกบริการไว้ในที่เดียว</b><small>ค้นหาง่าย ใช้งานสะดวก ปลอดภัย</small></div></div></div></div></div></section>
{user&&<section className="member-strip"><div className="container member-grid"><div><small>ยินดีต้อนรับกลับ</small><h2>สวัสดี คุณ{user.name.split(' ')[0]}</h2><p>ดูภาพรวมบริการและรายการที่เกี่ยวข้องกับคุณ</p><Link className="button primary" to="/dashboard">ไปยังแดชบอร์ด <ArrowRight/></Link></div><div className="member-stats"><div><b>3</b><span>คดีของฉัน</span></div><div><b>2</b><span>นัดหมายเร็ว ๆ นี้</span></div><div><b>1</b><span>คำร้องดำเนินการ</span></div><div><b>2</b><span><Bell/> แจ้งเตือน</span></div></div></div></section>}
<section className="section"><div className="container"><div className="section-head"><div><span className="section-kicker">บริการยอดนิยม</span><h2>บริการที่ใช้บ่อย</h2><p>เลือกจากสิ่งที่คุณต้องการทำได้ทันที</p></div><Link to="/services">ดูบริการทั้งหมด <ArrowRight/></Link></div><div className="audience-filters">{filters.map(x=><button className={filter===x.id?'active':''} onClick={()=>setFilter(x.id)} key={x.id}>{x.label}</button>)}</div>{featured.length?<div className="service-grid">{featured.map(s=><ServiceCard key={s.id} service={s}/>)}</div>:<div className="empty">ไม่พบบริการยอดนิยมสำหรับกลุ่มที่เลือก <Link to="/services">ดูบริการทั้งหมด</Link></div>}</div></section>
{user&&(favorites.length>0||recent.length>0)&&<section className="section soft"><div className="container"><div className="section-head"><div><span className="section-kicker">พื้นที่ของฉัน</span><h2>บริการของฉัน</h2></div></div>{favorites.length>0&&<><h3 className="subheading">รายการโปรด</h3><div className="service-grid">{favorites.slice(0,3).map(s=><ServiceCard key={s.id} service={s}/>)}</div></>}{recent.length>0&&<><h3 className="subheading">บริการที่ใช้ล่าสุด</h3><div className="recent-list">{recent.map(s=><Link to={`/service/${s.id}`} key={s.id}><s.icon/><span><b>{s.name}</b><small>{s.description}</small></span><ChevronRight/></Link>)}</div></>}</div></section>}
<section className="section category-section" id="categories"><div className="container"><div className="section-head centered"><div><span className="section-kicker">ค้นหาตามหมวดหมู่</span><h2>หมวดหมู่บริการ</h2><p>เลือกหมวดหมู่ที่ตรงกับสิ่งที่คุณกำลังมองหา</p></div></div><div className="category-grid">{categories.map(c=><button onClick={()=>nav(`/search?category=${encodeURIComponent(c.name)}`)} key={c.name}><span><c.icon/></span><div><b>{c.name}</b><small>{c.text}</small></div><ChevronRight/></button>)}</div></div></section><GuidedWizard/>
<section className="trust-section"><div className="container trust-grid"><div><b>เข้าถึงได้ทุกที่</b><span>รองรับมือถือ แท็บเล็ต และคอมพิวเตอร์</span></div><div><b>ข้อมูลปลอดภัย</b><span>ออกแบบโดยคำนึงถึงความเป็นส่วนตัว</span></div><div><b>พร้อมช่วยเหลือ</b><span>ศูนย์ช่วยเหลือในวันและเวลาราชการ</span></div></div></section></>}
