import { useState } from 'react'
import { Bell, ChevronDown, LogOut, Menu, Scale, UserRound, X } from 'lucide-react'
import { Link, NavLink, Outlet } from 'react-router-dom'
import { useApp } from '../App'
import { LoginModal } from '../components/LoginModal'

export function Layout(){const {user,logout,setLoginOpen}=useApp();const [menu,setMenu]=useState(false);return <div className="app-shell">
 <div className="demo-banner">เว็บไซต์นี้เป็นระบบสาธิต ข้อมูลทั้งหมดเป็นข้อมูลจำลอง</div>
 <header className="site-header"><div className="container header-inner"><Link to="/" className="brand"><span className="brand-mark"><Scale/></span><span><b>บริการออนไลน์ศาลยุติธรรม</b><small>Court Navigation Portal</small></span></Link>
 <nav className={menu?'main-nav open':'main-nav'} aria-label="เมนูหลัก"><NavLink to="/" onClick={()=>setMenu(false)}>หน้าหลัก</NavLink><NavLink to="/services" onClick={()=>setMenu(false)}>บริการทั้งหมด</NavLink><NavLink to="/popular" onClick={()=>setMenu(false)}>บริการยอดนิยม</NavLink><a href="/#guide" onClick={()=>setMenu(false)}>คู่มือการใช้งาน</a><a href="/#categories" onClick={()=>setMenu(false)}>ติดต่อศาล</a><a href="#footer" onClick={()=>setMenu(false)}>ช่วยเหลือ</a></nav>
 <div className="header-actions">{user?<><button className="notification-button" aria-label="การแจ้งเตือน"><Bell/><span>2</span></button><Link className="user-chip" to="/dashboard"><span className="avatar">{user.name[0]}</span><span className="user-text">สวัสดี<br/><b>คุณ{user.name.split(' ')[0]}</b></span><ChevronDown/></Link><button className="icon-button" onClick={logout} aria-label="ออกจากระบบ"><LogOut/></button></>:<><button className="button primary login-main" onClick={()=>setLoginOpen(true)}><UserRound/> เข้าสู่ระบบ</button><button className="button ghost hide-mobile" onClick={()=>setLoginOpen(true)}>ลงทะเบียน</button></>}<button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="เมนู">{menu?<X/>:<Menu/>}</button></div>
 </div></header><main><Outlet/></main>
 <footer id="footer"><div className="container footer-grid"><div><div className="brand footer-brand"><span className="brand-mark"><Scale/></span><span><b>บริการออนไลน์ศาลยุติธรรม</b><small>Court Navigation Portal</small></span></div><p>ศูนย์กลางนำทางสู่บริการออนไลน์ของศาล<br/>ใช้ง่าย ปลอดภัย เข้าถึงได้สำหรับทุกคน</p></div><div><b>บริการ</b><Link to="/services">บริการทั้งหมด</Link><Link to="/popular">บริการยอดนิยม</Link><a href="/#guide">ให้เราช่วยค้นหา</a><Link to="/search?q=คดี">ค้นหาบริการ</Link></div><div><b>ช่วยเหลือ</b><a href="#">คู่มือการใช้งาน</a><a href="#">คำถามที่พบบ่อย</a><a href="#">นโยบายความเป็นส่วนตัว</a></div><div><b>ศูนย์ช่วยเหลือ</b><strong className="hotline">1111</strong><span>วันจันทร์–ศุกร์ 08:30–16:30 น.</span></div></div><div className="container footer-bottom">© 2569 Court Navigation Portal — ระบบต้นแบบเพื่อการสาธิตเท่านั้น</div></footer><LoginModal/>
 </div>}
